controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_roll_joint
      - elbow_pan_joint
      - elbow_pitch_joint
      - gripper_pan_joint
      - gripper_pitch_joint
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - left_gripper_joint
      - right_gripper_joint
  - name: fake_base_group_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_arm_base_group_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_roll_joint
      - elbow_pan_joint
      - elbow_pitch_joint
      - gripper_pan_joint
      - gripper_pitch_joint
      - left_gripper_joint
      - right_gripper_joint
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: Home Pose