global_frame: odom
robot_base_frame: chassis
rolling_window: true
update_frequency: 10.0
publish_frequency: 5.0
transform_tolerance: 0.2

resolution: 0.05

# Robot footprint
footprint: [[-0.095, -0.095], [-0.095, 0.095], [0.095, 0.095], [0.095, -0.095]]
footprint_padding: 0.01

# Obstacle detection ranges
obstacle_range: 5.0
raytrace_range: 5.5

# Layer definitions
plugins:
  - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

obstacles_laser:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
  inflation_radius: 0.1
  cost_scaling_factor: 2.0
