global_frame: map
robot_base_frame: chassis
rolling_window: false
track_unknown_space: true

resolution: 0.05

# Obstacle detection ranges
obstacle_range: 5.0
raytrace_range: 5.5

# Robot footprint
footprint: [[-0.095, -0.095], [-0.095, 0.095], [0.095, 0.095], [0.095, -0.095]]
footprint_padding: 0.01

# Layer definitions
plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

static:
  map_topic: /map
  subscribe_to_updates: true

inflation:
  inflation_radius: 0.3
  cost_scaling_factor: 5.0
