footprint: [[-0.095, -0.095], [-0.095, 0.095], [0.095, 0.095], [0.095, -0.095]]

footprint_padding: 0.01

robot_base_frame: chassis
update_frequency: 10.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.0
raytrace_range: 5.5

# Layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.1
