controller_frequency: 10.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: true
  default_tolerance: 0.05

TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 1.5
  acc_lim_theta: 2.5

  max_vel_x: 0.3
  min_vel_x: 0.0

  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.3

  holonomic_robot: false
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.5
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: true
  occdist_scale: 0.2
  pdist_scale: 0.8
  gdist_scale: 1.0

  heading_lookahead: 0.3
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  simple_attractor: false
  publish_cost_grid_pc: true

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.1
  escape_reset_dist: 0.05
  escape_reset_theta: 0.05

DWAPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 1.5
  acc_lim_y: 0
  acc_lim_th: 2.5

  max_vel_x: 0.3
  min_vel_x: 0.0

  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 0.3
  min_trans_vel: 0.1
  max_rot_vel: 0.8
  min_rot_vel: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Trajectory scoring parameters
  path_distance_bias: 20.0
  goal_distance_bias: 18.0
  occdist_scale: 0.2
  forward_point_distance: 0.15
  stop_time_buffer: 0.2
  scaling_speed: 0.15
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.1
